name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.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 }}
        run: |
          git config user.email "70110589@student.uol.edu.pk"
          git config user.name "Sakina122"
          git add .
          git commit -m "Sync to Hugging Face Hub"
          git push https://Sakina122:${HF_TOKEN}@huggingface.co/spaces/sakinafatima123/image-to-text-app main
